name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: Build ElmUiView
    runs-on: ubuntu-latest

    steps:
    - name: Set up Elm
      uses: jorelali/setup-elm@v1
      with:
        elm-version: 0.19
      
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Build ElmUiView
      run: elm make src/ElmUiView.elm
