name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: Build ElmUiView
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up Elm
      run: sh scripts/install_elm.sh
      

    - name: Build ElmUiView
      run: elm make src/ElmUiView.elm
