name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install elm
      run: npm install --unsafe-perm -g elm@0.19.0-no-deps
    - name: Build ElmUiView
      run: elm make src/ElmUiView.elm
